apiVersion: v1
kind: PersistentVolume
metadata:
  name: longhorn-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  hostPath:
    path: /mnt/disks/longhorn-pv
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn

---
apiVersion: v1
kind: Pod
metadata:
  name: longhorn-pod
spec:
  containers:
    - name: my-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: longhorn-storage
  volumes:
    - name: longhorn-storage
      persistentVolumeClaim:
        claimName: longhorn-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: longhorn-service
spec:
  selector:
    app: longhorn-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

