apiVersion: v1
kind: Pod
metadata:
  name: v-test
  namespace: default
  labels:
    app: longhorn-pod
spec:
  containers:
  - name: v-test
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: vupvc

---
apiVersion: v1
kind: Service
metadata:
  name: longhorn-service
spec:
  selector:
    app: longhorn-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
