apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-2
  template:
    metadata:
      labels:
        app: myapp-2
    spec:
      nodeSelector:
        kubernetes.io/hostname: nodes-one
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
      - name: mysql-container
        image: mysql:latest  # Sử dụng image MySQL phiên bản 5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "yourpassword123"  # Đặt mật khẩu root cho MySQL
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: my-service-2
spec:
  selector:
    app: myapp-2
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 80
      nodePort: 30002
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: myapp-2
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 31002
  type: NodePort
