apiVersion: v1
kind: Pod
metadata:
  name: v-test-pod
spec:
  containers:
  - name: v-test-container
    image: nginx:latest
    volumeMounts:
    - name: vupvc
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: vupvc
    persistentVolumeClaim:
      claimName: vu

