# PersistentVolume cho MySQL
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/mysql"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - nodes-two
---
# PersistentVolumeClaim cho MySQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Deployment cho MySQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-4
  template:
    metadata:
      labels:
        app: myapp-4
    spec:
      nodeSelector:
        kubernetes.io/hostname: nodes-two
      containers:
      - name: mysql-container
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "yourpassword123"  # Đặt mật khẩu cho MySQL
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-storage
      - name: hethonghoc-container
        image: vudinh112/he_thong_hoc:v13
        env:
        - name: MYSQL_HOST
          value: "mysql-service-4"  # Tên dịch vụ MySQL
        ports:
        - containerPort: 2002
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc-2  # Sử dụng PVC đã định nghĩa
---
# Service cho MySQL
apiVersion: v1
kind: Service
metadata:
  name: mysql-service-4
spec:
  selector:
    app: myapp-4  # Chọn các pod có nhãn app: myapp-4
  ports:
    - protocol: TCP
      port: 3306      # Port mà dịch vụ sẽ lắng nghe
      targetPort: 3306  # Port mà MySQL đang lắng nghe
  type: ClusterIP   # Sử dụng ClusterIP để kết nối nội bộ
---
# Service cho frontend
apiVersion: v1
kind: Service
metadata:
  name: my-service-4
spec:
  selector:
    app: myapp-4  # Chọn các pod có nhãn app: myapp-4
  ports:
    - protocol: TCP
      port: 3004     # Port mà dịch vụ sẽ lắng nghe
      targetPort: 2002  # Port mà ứng dụng frontend đang lắng nghe
  type: NodePort    # Sử dụng NodePort để truy cập từ bên ngoài
